# This is a basic workflow to help you get started with Actions

name: Workflow!!!

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Haxelib Stuff
        run: |
          haxelib install lime
          haxelib install flixel
          haxelib install openfl
          haxelib install flixel-addons
          haxelib run lime setup
      - name: Compile
        run: haxelib run lime build html5
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: html5Build
          path: export/release/html5/bin
